export { default as Actors } from './Actors/Actors'
export { default as MovieInfo } from './MovieInformation/MovieInfo'
export { default as Profile } from './Profile/Profile'
export { default as Movies } from './Movies/Movies'
export { default as NavBar } from './NavBar/NavBar'